In [3]:
import numpy as np

with open('1268-0.txt','r',encoding="utf-8") as f:
    text = f.read()
start_indx = text.find('THE MYSTERIOUS ISLAND')
end_indx = text.find('End of the Project Gutenberg')
text = text[start_indx:end_indx]
char_set = set(text)
print('Total Length:',len(text))
print('Unique Characters:',len(char_set))

Total Length: 1130711
Unique Characters: 85


In [4]:
chars_sorted = sorted(char_set)
char2int = {ch:i for i,ch in enumerate(chars_sorted)}
char_array = np.array(chars_sorted)
text_encoded = np.array([char2int[ch] for ch in text],dtype=np.int32)
print('Text encoded shape:',text_encoded.shape)

Text encoded shape: (1130711,)


In [5]:
chars_sorted

['\n',
 ' ',
 '!',
 '"',
 '$',
 '%',
 '&',
 "'",
 '(',
 ')',
 '*',
 ',',
 '-',
 '.',
 '/',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '=',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '‘',
 '’',
 '“',
 '”']

In [8]:
text[:15]

'THE MYSTERIOUS '

In [9]:
char_array

array(['\n', ' ', '!', '"', '$', '%', '&', "'", '(', ')', '*', ',', '-',
       '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':',
       ';', '=', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J',
       'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W',
       'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j',
       'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w',
       'x', 'y', 'z', '‘', '’', '“', '”'], dtype='<U1')

In [10]:
print(text[:15],'= Encoding => ',text_encoded[:15])
print(text_encoded[15:21],'== Reverse ==>',
      ''.join(char_array[text_encoded[15:21]]))

THE MYSTERIOUS  = Encoding =>  [48 36 33  1 41 53 47 48 33 46 37 43 49 47  1]
[37 47 40 29 42 32] == Reverse ==> ISLAND


In [11]:
for ex in text_encoded[:5]:
    print('{} - > {}'.format(ex,char_array[ex]))

48 - > T
36 - > H
33 - > E
1 - >  
41 - > M


In [12]:
import torch
from torch.utils.data import Dataset
seq_length = 40
chunk_size = seq_length + 1
text_chunks = [text_encoded[i:i+chunk_size]
               for i in range(len(text_encoded)-chunk_size)]

In [13]:
text_chunks

[array([48, 36, 33,  1, 41, 53, 47, 48, 33, 46, 37, 43, 49, 47,  1, 37, 47,
        40, 29, 42, 32,  1, 10, 10, 10,  0,  0,  0,  0,  0, 48, 36, 33,  1,
        41, 53, 47, 48, 33, 46, 37], dtype=int32),
 array([36, 33,  1, 41, 53, 47, 48, 33, 46, 37, 43, 49, 47,  1, 37, 47, 40,
        29, 42, 32,  1, 10, 10, 10,  0,  0,  0,  0,  0, 48, 36, 33,  1, 41,
        53, 47, 48, 33, 46, 37, 43], dtype=int32),
 array([33,  1, 41, 53, 47, 48, 33, 46, 37, 43, 49, 47,  1, 37, 47, 40, 29,
        42, 32,  1, 10, 10, 10,  0,  0,  0,  0,  0, 48, 36, 33,  1, 41, 53,
        47, 48, 33, 46, 37, 43, 49], dtype=int32),
 array([ 1, 41, 53, 47, 48, 33, 46, 37, 43, 49, 47,  1, 37, 47, 40, 29, 42,
        32,  1, 10, 10, 10,  0,  0,  0,  0,  0, 48, 36, 33,  1, 41, 53, 47,
        48, 33, 46, 37, 43, 49, 47], dtype=int32),
 array([41, 53, 47, 48, 33, 46, 37, 43, 49, 47,  1, 37, 47, 40, 29, 42, 32,
         1, 10, 10, 10,  0,  0,  0,  0,  0, 48, 36, 33,  1, 41, 53, 47, 48,
        33, 46, 37, 43, 49, 47,  1],

In [14]:
class TextDataset(Dataset):
    def __init__(self,text_chunks):
        self.text_chunks = text_chunks
    
    def __len__(self):
        return len(self.text_chunks)
    
    def __getitem__(self,idx):
        text_chunk = self.text_chunks[idx]
        return text_chunk[:-1].long(),text_chunk[1:].long()
seq_dataset = TextDataset(torch.tensor(text_chunks))
        

/tmp/ipykernel_32072/3956906441.py:11: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ../torch/csrc/utils/tensor_new.cpp:261.)
  seq_dataset = TextDataset(torch.tensor(text_chunks))


In [15]:
for i, (seq,target) in enumerate(seq_dataset):
    print(' Input (x):',repr(''.join(char_array[seq])))
    print('Target (y):',repr(''.join(char_array[target])))
    print()
    if i==1:
        break

 Input (x): 'THE MYSTERIOUS ISLAND ***\n\n\n\n\nTHE MYSTER'
Target (y): 'HE MYSTERIOUS ISLAND ***\n\n\n\n\nTHE MYSTERI'

 Input (x): 'HE MYSTERIOUS ISLAND ***\n\n\n\n\nTHE MYSTERI'
Target (y): 'E MYSTERIOUS ISLAND ***\n\n\n\n\nTHE MYSTERIO'



In [16]:
from torch.utils.data import DataLoader
batch_size =64
torch.manual_seed(1)
seq_dl = DataLoader(seq_dataset,batch_size=batch_size,
                    shuffle=True,drop_last=True)

Building a character-level RNN model

In [17]:
import torch.nn as nn
class RNN(nn.Module):
    def __init__(self,vocab_size,embed_dim,rnn_hidden_size):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size,embed_dim)
        self.rnn_hidden_size = rnn_hidden_size
        self.rnn = nn.LSTM(embed_dim,rnn_hidden_size,
                          batch_first=True)
        self.fc = nn.Linear(rnn_hidden_size,vocab_size)
        self.softmax = nn.LogSoftmax(dim=1)
        
    def forward(self,x,hidden,cell):
        out = self.embedding(x).unsqueeze(1)
        out,(hidden,cell) = self.rnn(out,(hidden,cell))
        out = self.fc(out).reshape(out.size(0),-1)
        return out,hidden,cell
    
    def init_hidden(self,batch_size):
        hidden = torch.zeros(1,batch_size,self.rnn_hidden_size)
        cell = torch.zeros(1,batch_size,self.rnn_hidden_size)
        return hidden, cell
        

In [15]:
vocab_size = len(char_array)
embed_dim = 256
rnn_hidden_size = 512
torch.manual_seed(1)
model = RNN(vocab_size,embed_dim,rnn_hidden_size)
model

RNN(
  (embedding): Embedding(85, 256)
  (rnn): LSTM(256, 512, batch_first=True)
  (fc): Linear(in_features=512, out_features=85, bias=True)
  (softmax): LogSoftmax(dim=1)
)

In [16]:
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(),lr=0.001)

In [17]:
num_epochs=10000
torch.manual_seed(1)
for epoch in range(num_epochs):
    hidden,cell = model.init_hidden(batch_size)
    seq_batch,target_batch = next(iter(seq_dl))
    optimizer.zero_grad()
    loss=0
    for c in range(seq_length):
        pred,hidden,cell = model(seq_batch[:,c],hidden,cell)
        loss += loss_fn(pred,target_batch[:,c])
    loss.backward()
    optimizer.step()
    loss = loss.item()/seq_length
    if epoch %500 == 0:
        print(f'Epoch {epoch} loss : {loss:.4f}')

Epoch 0 loss : 4.4368
Epoch 500 loss : 1.4892
Epoch 1000 loss : 1.3265
Epoch 1500 loss : 1.3372
Epoch 2000 loss : 1.2138
Epoch 2500 loss : 1.2308
Epoch 3000 loss : 1.1979
Epoch 3500 loss : 1.1676
Epoch 4000 loss : 1.1639
Epoch 4500 loss : 1.1399
Epoch 5000 loss : 1.1074
Epoch 5500 loss : 1.0503
Epoch 6000 loss : 1.1310
Epoch 6500 loss : 1.0810
Epoch 7000 loss : 1.0650
Epoch 7500 loss : 1.0693
Epoch 8000 loss : 1.0790
Epoch 8500 loss : 1.0242
Epoch 9000 loss : 0.9855
Epoch 9500 loss : 1.1050


In [7]:
from torch.distributions.categorical import Categorical
torch.manual_seed(1)
logits = torch.tensor([[1.0,1.0,1.0]])
print('Probabilities:',nn.functional.softmax(logits,dim=1).numpy[0])


NameError: name 'torch' is not defined